GET https://capstone-project-405913.et.r.appspot.com
###
POST https://capstone-project-405913.et.r.appspot.com
Content-Type: application/json

{
    "name": "pisang",
    "vitamin":"vitamin A",
    "kaduluarsa":"5 Hari",
    "saran penyimpanan":"tempat lembab"
}
###
DELETE  https://capstone-project-405913.et.r.appspot.com

###
PUT https://capstone-project-405913.et.r.appspot.com
Content-Type: application/json  
{
    "name": "pisang",
    "vitamin":"vitamin A",
    "kaduluarsa":"5 Hari",
    "saran penyimpanan":"tempat lembab"
}